### ISSUE TITLE
Forking the repo and renaming it no longer renders the website properly.

### ISSUE THREAD

**Issue by denialromeo** [henrythemes/jekyll-minimal-theme#2]

**Comment by geraldb** [comment]
@danielvmoore Thanks for reporting and trying. In `_config.yml` change:

```
path: /jekyll-minimal-theme  
url:  'http://henrythemes.github.io/jekyll-minimal-theme'
```

to your repo settings. Cheers. PS: Will try to update the theme to the new baseurl / url Jekyll 3.3 conventions in the next days. Thanks for the reminder and patience.
