### ISSUE TITLE
Demo 404

### ISSUE THREAD

**Issue by sadegr** [henrythemes/jekyll-minimal-theme#4]
The Demo button on http://jekyllthemes.org/themes/drjekyll-minimal/ links to http://drjekyllthemes.github.io/jekyll-minimal-theme/, which is showing an HTTP 404 error.

**Comment by geraldb** [comment]
Thanks for reporting - the correct link is <http://henrythemes.github.io/jekyll-minimal-theme/> change drjekyllthemes to henrythemes. Please use the alternative (more up-to-date) Dr Jekyll's theme directory / listing, see <http://drjekyllthemes.github.io> :-).

**Comment by sadegr** [comment]
Thanks! Nice theme as well.
